[2025-05-26T15:11:09.601+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T08:12:00+00:00 [queued]>
[2025-05-26T15:11:09.606+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T08:12:00+00:00 [queued]>
[2025-05-26T15:11:09.607+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:11:09.614+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task3> on 2025-05-26 08:12:00+00:00
[2025-05-26T15:11:09.616+0000] {standard_task_runner.py:57} INFO - Started process 4386 to run task
[2025-05-26T15:11:09.618+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task3', 'scheduled__2025-05-26T08:12:00+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp6viz6avl']
[2025-05-26T15:11:09.619+0000] {standard_task_runner.py:85} INFO - Job 509: Subtask task3
[2025-05-26T15:11:09.627+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:11:09.646+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task3 scheduled__2025-05-26T08:12:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:11:09.682+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T08:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T08:12:00+00:00'
[2025-05-26T15:11:09.683+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:11:09.683+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the third task!']
[2025-05-26T15:11:09.688+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:11:09.688+0000] {subprocess.py:93} INFO - Hello world, this is the third task!
[2025-05-26T15:11:09.689+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:11:09.699+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task3, execution_date=20250526T081200, start_date=20250526T151109, end_date=20250526T151109
[2025-05-26T15:11:09.717+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:11:09.728+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
