[2025-05-26T15:11:58.484+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T15:06:00+00:00 [queued]>
[2025-05-26T15:11:58.489+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T15:06:00+00:00 [queued]>
[2025-05-26T15:11:58.489+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:11:58.496+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task3> on 2025-05-26 15:06:00+00:00
[2025-05-26T15:11:58.501+0000] {standard_task_runner.py:57} INFO - Started process 5613 to run task
[2025-05-26T15:11:58.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task3', 'scheduled__2025-05-26T15:06:00+00:00', '--job-id', '908', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpf5qmgach']
[2025-05-26T15:11:58.504+0000] {standard_task_runner.py:85} INFO - Job 908: Subtask task3
[2025-05-26T15:11:58.512+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:11:58.530+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task3 scheduled__2025-05-26T15:06:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:11:58.570+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T15:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T15:06:00+00:00'
[2025-05-26T15:11:58.570+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:11:58.571+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the third task!']
[2025-05-26T15:11:58.575+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:11:58.576+0000] {subprocess.py:93} INFO - Hello world, this is the third task!
[2025-05-26T15:11:58.576+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:11:58.590+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task3, execution_date=20250526T150600, start_date=20250526T151158, end_date=20250526T151158
[2025-05-26T15:11:58.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:11:58.612+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
